
		<br /><br />
			<div id="view-content" class='wiki'>		
				    <h1 align="center">Add Category</h1>
				    
				    <form valign="top" align="center" id="category_form" action="<?php echo $this->escape($this->form->getAction()) ?>"
			              method="<?php echo $this->escape($this->form->getMethod()) ?>"
			              enctype="multipart/form-data">
					        <table align="center" class="category_table">
					            <tbody>
					                <tr>
					                    <td><?php echo $this->form->cname; ?></td>
					                </tr>
					             	<tr>
					                    <td><?php echo $this->form->status; ?></td>
					                </tr>
					                <tr>
					                    <td><?php echo $this->form->parent_id; ?></td>
					                </tr>
					                <tr>
					                	<td ><a class="button-style" href="/wiki/index/category">Back</a></td>
					                    <td style="text-align: right;"><?php echo $this->form->submit; ?></td>
					                </tr>
					            </tbody>
					        </table>
				 </form>
			</div>


