<br /><br />
<div id="view-content">
    <h1 align="center">Categories</h1>
	<div style="margin-left:10%">
		<ol>
				<?php if($this->parentCategories):?>
					<?php foreach($this->parentCategories as $key => $val):?>
							<h3><a href=""><?php echo $val['category_name'] ?></a></h3>
							<ul>
								<?php if($this->subCategories):?>
									<?php foreach($this->subCategories as $subkey => $subval):?>
										<?php if($subval['category_parent'] == $val['category_id']):?>
											<li><a href=""><?php echo $subval['category_name'] ?></a></li>
										<?php endif;?>	
									<?php endforeach;?>	
								<?php endif;?>	
							</ul>
					<?php endforeach;?>	
				<?php endif;?>		
		</ol>
		
	</div>
	
</div>