<br /><br />
<div id="view-content" class='wiki'>
	<div class='content'>
	    <h1 align="center">Categories</h1>
		<div id="category_list">
			<ol>
					<?php if($this->parentCategories):?>
						<?php foreach($this->parentCategories as $key => $val):?>
								<h3><a href=""><?php echo $val['category_name'] ?></a></h3>
								<ul>
									<?php if($this->subCategories):?>
										<?php foreach($this->subCategories as $subkey => $subval):?>
											<?php if($subval['category_parent'] == $val['category_id']):?>
												<li><a href=""><?php echo $subval['category_name'] ?></a></li>
											<?php endif;?>	
										<?php endforeach;?>	
									<?php endif;?>	
								</ul>
						<?php endforeach;?>	
					<?php endif;?>		
			</ol>
			
			<div align="bottom" valign="bottom" class="buttonMenuBottom">
				<table width="80%" align="center" cellspacing="1">
					<tbody>
						<tr>
							<td><a class="button-style" href="/wiki/index/add-category">Add Category</a></td>
							<td><a class="button-style" href="/wiki/index/edit-category">Edit Category</a></td>
							<td><a class="button-style" href="/wiki/index/delete-category">Remove Category</a></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	
	
</div>