	<br /><br />
<div id="view-content">
        <h1 align="center">Contributor</h1>
		<div align="center">
			<?php if($this->contributor):?>
				<?php foreach($this->contributor as $key => $val):?>
					<h2>Topic Contributions by <?=$val['contributor_name']?></h1>
				<?php endforeach;?>	
			<?php endif;?>	
				<table width="60%" align="center" cellspacing="1" border="1px">
					<tbody>
							<tr>
								<td class="form-title" width="70%" style="text-align: left;">Topic</td>
								<td class="form-title" width="30%" style="text-align: left;">Date</td>
							</tr>
					</tbody>
				</table>
		</div>

</div>
	