	<br /><br />
<div id="view-content">
        <h1 align="center">Contributor</h1>
		<div align="center">
			<?php if($this->contributor):?>
				<?php foreach($this->contributor as $key => $val):?>
					<h2>Topic Contributions by <?=$val['contributor_name']?></h1>
				<?php endforeach;?>	
			<?php endif;?>	
				<table width="60%" align="center" cellspacing="1">
					<tbody>
							<tr>
								<td class="form-title" width="60%" style="text-align: left;">Topic</td>
								<td class="form-title" width="20%" style="text-align: left;">Date</td>
							</tr>
							<?php if($this->all_topics):?>
								<?php foreach($this->all_topics as $key => $val):?>
									<tr>
										<td><?=$val['topic_title']?></td>
										<td><?=$val['date_created']?></td>
									</tr>	
								<?php endforeach;?>			
							<?php endif;?>	
					</tbody>
				</table>
		</div>
		<div align="right" style="margin-right: 10%">
			<?php if($this->p_urls):?>
						<?php foreach($this->p_urls as $key => $val):?>
									<a href=<?=$val?>><?= $key?></a>
						<?php endforeach;?>	
			<?php endif; ?>
		</div>
</div>
	