<br /><br />
<div id="view-content">
        <h1 align="center">Contributions</h1>
	<div>
		<table width="80%" align="center" cellspacing="1">
			<tbody>
				<tr>
					<td class="form-title" width="30%" style="text-align: left;">Department</td>
					<td class="form-title" width="40%" style="text-align: left;">Name</td>
					<td class="form-title" width="30%" style="text-align: left;">Contribution</td>
				</tr>
				<?php if($this->contributor_array):?>
					<?php foreach($this->contributor_array as $key => $val):?>
						<tr class="row-1">
							<td><?=$val['department_name']?></td>
							<td><a href="/wiki/index/show-contributor/?userid=<?=$val['contributor_id']?>"><?=$val['contributor_name']?></a></td>
							<td><a href="/wiki/index/contributions/?userid=<?=$val['contributor_id']?>"><?=$val['contributions']?></a></td>
						</tr>
					<?php endforeach;?>			
				<?php endif;?>
			</tbody>
		</table>
	</div>
	<div align="right" style="margin-right: 10%">
		<?php if($this->pages):?>
			
					<?php for($i = 1; $i<$this->pages+1; $i++):?>
						<a href="?page=<?=$i?>"> <?= $i?></a>
					<?php endfor;?>	
		<?php endif; ?>

	</div>
</div>