<div class='wiki'>
    <h1>
        <?php echo $this->data['title'] ?>
    </h1>
    <h4>
        Author:<?php echo $this->data['realname'] ?>
    </h4>
    <h4>
        Create Time:<?php echo $this->data['create_time'] ?>
    </h4>
    <h4>
        Last Update Time:<?php echo $this->data['update_time'] ?>
    </h4>
    <div>
        <?php echo $this->data['content'] ?>
    </div>
</div>
