
		<br /><br />
			<div id="view-content" class='wiki'>		
				    <h1 align="center">Edit Category</h1>
				   <div id="category_list"> 
				   	<h3>Select Category to Edit</h3>
					<?php if($this->parentCategories):?>
						<?php foreach($this->parentCategories as $key => $val):?>
								<h3><a class="categoryLink" value="<?php echo $val['category_id'] ?>"><?php echo $val['category_name'] ?></a></h3>
									<input type="hidden" class="<?php echo $val['category_id'] ?>" value="<?php echo $val['category_name'] ?>" />
									<input type="hidden" class="<?php echo $val['category_id'] ?>" value="<?php echo $val['category_status'] ?>" />
									<input type="hidden" class="<?php echo $val['category_id'] ?>" value="<?php echo $val['category_parent'] ?>" />
									<input type="hidden" class="<?php echo $val['category_id'] ?>" value="<?php echo $val['category_id'] ?>" />
								<ul>
									<?php if($this->subCategories):?>
										<?php foreach($this->subCategories as $subkey => $subval):?>
											<?php if($subval['category_parent'] == $val['category_id']):?>
												<li>
													<a class="categoryLink" value="<?php echo $subval['category_id'] ?>" ><?php echo $subval['category_name'] ?></a>
													<input type="hidden" class="<?php echo $subval['category_id'] ?>" value="<?php echo $subval['category_name'] ?>" />
													<input type="hidden" class="<?php echo $subval['category_id'] ?>" value="<?php echo $subval['category_status'] ?>" />
													<input type="hidden" class="<?php echo $subval['category_id'] ?>" value="<?php echo $subval['category_parent'] ?>" />
													<input type="hidden" class="<?php echo $subval['category_id'] ?>" value="<?php echo $subval['category_id'] ?>" />
												</li>
											<?php endif;?>	
										<?php endforeach;?>	
									<?php endif;?>	
								</ul>
						<?php endforeach;?>	
					<?php endif;?>		
			</ol>
				   </div>
				 	<div id="edit_form">		   
				    <form valign="top" align="center" id="category_form" action="<?php echo $this->escape($this->form->getAction()) ?>"
			              method="<?php echo $this->escape($this->form->getMethod()) ?>"
			              enctype="multipart/form-data">
					        <table align="center" class="category_table">
					            <tbody>
					                <tr>
					                    <td id="categoryName"><?php echo $this->form->cname; ?></td>
					                </tr>
					             	<tr>
					                    <td id="categoryStatus"><?php echo $this->form->status; ?></td>
					                </tr>
					                <tr>
					                    <td id="categoryParentID"><?php echo $this->form->parent_id; ?></td>
					                </tr>
					                <tr>
					                    <td id="categoryID"><?php echo $this->form->category_id; ?></td>
					                </tr>
					                <tr>
					                	<td ><a class="button-style" href="/wiki/index/category">Back</a></td>
					                    <td style="text-align: right;"><?php echo $this->form->submit; ?></td>
					                </tr>
					            </tbody>
					        </table>
				 </form>
			</div>
				 
			</div>
			
<script type="text/javascript">

$(document).ready(function(){
       console.log("Test");
	       $(".categoryLink").click(function(){

	       var id = $(this).attr('value');
	       var inputs = [];
	       inputs = $("input."+id).map(function(){ return $(this).val();}).get();
	       $("input#cname").val(inputs[0]);
	       $("input#status").val(inputs[1]);
	       $("input#parent_id").val(inputs[2]);
	       $("input#category_id").val(inputs[3]);
        });
      
       
        });

</script>

