<?php
$this->Scripts = <<<EOF
<script type="text/javascript" src="/scripts/ckeditor4.2/ckeditor.js"></script>
<script type="text/javascript">
    $(function(){
        $('#title').click(function(){
            $(this).select();
            $(this).css('color','#000')

        });

        $('#content').focus();
        $('#topic_form').submit(function(){
            if(!CKEDITOR.instances.content.checkDirty()){
                alert('It seem no need to submit,because the content do not change:)');
                return false;
            } else {
                return true;
            }
        }); 
    });
</script>
EOF;
?>


<div class="wiki">
    <?php if(isset($this->message)):?>
        <div class="message ui-widget ui-widget-content ui-corner-all"><?php echo $this->message ?></div>
        <script></script>
    <?php endif;?>
    <form id="topic_form" action="<?php echo $this->escape($this->form->getAction()) ?>"
              method="<?php echo $this->escape($this->form->getMethod()) ?>"
              enctype="multipart/form-data">
        <table width="100%">
            <tbody>
                <tr>
                    <td valign="top"><?php echo $this->form->title; ?></td>
                    <td valign="top" width="30%"><?php echo $this->form->category; ?></td>
                </tr>
                <tr>
                    <td colspan="2">
                        <?php echo $this->form->content; ?>
                        <?php echo $this->form->tid; ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align: right;"><button class="back" onclick="location.href='/wiki/index/detail/id/<?php echo $this->tid;?>';return false;">back to topic</button><?php echo $this->form->submit; ?></td>
                </tr>
            </tbody>
        </table>
    </form>
    <script type="text/javascript">
        CKEDITOR.replace('content',{
            extraPlugins: 'autogrow',
            height:'500px',
            filebrowserBrowseUrl: '/scripts/ckfinder/ckfinder.html',
            filebrowserImageBrowseUrl: '/scripts/ckfinder/ckfinder.html?Type=Images',
            filebrowserFlashBrowseUrl: '/scripts/ckfinder/ckfinder.html?Type=Flash',
            filebrowserUploadUrl: '/scripts/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
            filebrowserImageUploadUrl: '/scripts/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
            filebrowserFlashUploadUrl: '/scripts/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
        });
    </script>
</div>