<div class="wiki">
    <div class="history tb-style">
<!--        <pre><?//=print_r($this->data)?></pre>-->
        <table width="100%" cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <th>Version</th>
                    <th>Update Time</th>
                    <th>Contributor</th>
                    <th>Topic</th>
                </tr>
                <?php foreach ($this->data as $value):?>
                <tr>
                    <td><?php echo $value['version_id'] ?></td>
                    <td><?php echo $value['update_time'] ?></td>
                    <td><?php echo $value['update_name'] ?></td>
                    <td><a href="/wiki/index/detail/id/<?php echo $value['id'];?>"><?php echo $value['title'] ?></a></td>
                </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    </div>
</div>
