<?php
$this->Css = <<<EOF
    <link type="text/css" rel="stylesheet" href="/scripts/ckeditor4.2/contents_view.css">        
EOF;
?>
<div class='wiki'>
    <div class="detail">
        <div class="tool-bar">
            <div class="fr">
                <span class="ui-icon ui-icon-arrowthick-1-w fl"></span>
                <a href="/wiki/index/history/id/<?php echo  $this->data['id']; ?>" style="line-height: 16px;">Back to history</a>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
        <h1 class="title">
        <?php echo $this->data['title']; if($this->data['is_default']==TRUE) echo '<i style="color:#CF1E1E;font-size:12px;">(Current Version)</i>'; ?>
        </h1>
        <h4 class="info">
            Author:<?php echo $this->data['creator_name'] ?>&nbsp;|&nbsp;
            Create Time:<?php echo $this->data['create_time'] ?>&nbsp;|&nbsp;
            Last Update Time:<?php echo $this->data['update_time'] ?>&nbsp;|&nbsp;
            Update By:<?php echo $this->data['update_name'] ?>
        </h4>
        <div class="content cke_editable cke_editable_themed cke_contents_ltr cke_show_borders">
            <?php echo $this->data['content'] ?>
        </div>
        <div class="handle">
            <table>
                <tbody>
                    <tr>
                        <?php if($this->data['prevId']!=NULL):?>
                        <td><a class="button-style" href="/wiki/index/revert/id/<?php echo  $this->data['id'];?>/version/<?php echo  $this->data['prevId'];?>">Previous Version</a></td>
                        <?php endif; ?>
                        <?php if($this->data['nextId']!=NULL):?>
                        <td><a class="button-style" href="/wiki/index/revert/id/<?php echo  $this->data['id'];?>/version/<?php echo  $this->data['nextId'];?>">Next Version</a></td>
                        <?php endif; ?>
                        <?php if($this->data['is_default']!=TRUE):?>
                        <?php $uid = Zend_Auth::getInstance()->getStorage()->read()->id?>
                        <?php if($this->data['creator_uid']===$uid):?><td><a id="delete" class="button-style" href="/wiki/index/set-default/id/<?php echo $this->data['tid'] ?>/version/<?php echo $this->data['version_id'];?>">Revert to this version</a></td><?php endif;?>
                        <script type="text/javascript">
                             $('#delete').click(function(){
                                 if(confirm("Are you sure to revert this version?")){
                                     return true;
                                 }
                                 return false;
                             });
                        </script>
                        <?php endif; ?>
                    </tr>
                </tbody>
            </table>
        </div>
         <div class="tool-bar">
        <div class="fr">
            <span class="ui-icon ui-icon-arrowthick-1-w fl"></span>
            <a href="/wiki/index/history/id/<?php echo $this->data['id']; ?>" style="line-height: 16px;">Back to history</a>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
    </div>
   
</div>
<!--<pre><?//=print_r($this->data)?></pre>-->