<br /><br />
<div id="view-content">
        <h1 align="center">Contributor</h1>
	<div>
		<div style="margin-left: 10%">
				<?php if($this->contributor):?>
					<?php foreach($this->contributor as $key => $val):?>
							<h3>Name:</h3><?=$val['contributor_name']?>
							<h3>Department:</h3><?=$val['department_name']?>
							<h3>Total Contributions:</h3><?=$val['contributions']?>
					<?php endforeach;?>			
				<?php endif;?>
		</div>
		<div align="center">
		<h2>Latest Topic Contributions</h1>
				<table width="60%" align="center" cellspacing="1" >
					<tbody>
							<tr>
								<td class="form-title" width="70%" style="text-align: left;">Topic</td>
								<td class="form-title" width="30%" style="text-align: left;">Date</td>
							</tr>
					</tbody>
				</table>
		</div>
</div>