<div align="center">

<table class="hide" border="0" cellpadding="0" cellspacing="3">
	<tbody>
		<tr>
			<td valign="top" width="100%">
				<table class="width100" cellspacing="1">
					<tbody>
						<tr>
							<td class="form-title">Project Name</td>
							<td class="form-title">Status</td>
							<td class="form-title">Creator</td>
							<td class="form-title">Create Time</td>
							<td class="form-title">Action</td>
						</tr>
						<?php if($this->list):
								$n = 1;
								foreach($this->list as $list):
						?>
						<tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
							<td class="center"><span class="small"><?=$list['project_name']?></span></td>
							<td class="center"><span class="small"><?=$list['status']?></span></td>
							<td class="center"><span class="small"><?=$list['creator']?></span></td>
							<td class="center"><span class="small"><?=$list['create_time']?></span></td>
							<td class="center"><span class="small"><a href="/projects/edit/id/<?=$list['id']?>">Edit</a></span></td>
						</tr>
						<?php
								endforeach;
							endif;
						?>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>
</div>
