		<br /><br />
			<div id="view-content" class='wiki'>		
				    <h1 align="center">Delete Category</h1>
				   <div id="category_list"> 
				   	<h3>Select Category to Delete</h3>
					<?php if($this->categories):?>
						<?php echo $this->categories; ?>
					<?php endif;?>	
			
				<div id="delete_form" >		   
				    <form valign="top" align="center" id="category_form" action="<?php echo $this->escape($this->form->getAction()) ?>"
			              method="<?php echo $this->escape($this->form->getMethod()) ?>"
			              enctype="multipart/form-data">
					        <table align="center" class="category_table">
					            <tbody>
					                <tr>
					                    <td id="categoryID"><?php echo $this->form->category_id; ?></td>
					                </tr>
					                <tr>
					                	<td ><a class="button-style" href="/wiki/category">Back</a></td>
					                    <td style="text-align: right;"><?php echo $this->form->submit; ?></td>
					                       <td><span id="deleteMessage">
											   	<label>Category to be Deleted: </label><p id="outputID"></p>
											 </span>
											 </td>
					                </tr>
					            </tbody>
					        </table>
				 </form>
			</div>
			

			
				   </div>
				   

				   
<script type="text/javascript">

$(document).ready(function(){

	       $(".categoryLink").click(function(){

	       var id = $(this).attr('value');
	       var inputs = [];
	       inputs = $("input."+id).map(function(){ return $(this).val();}).get();
	       $("input#category_id").val(inputs[3]);
	       $("#outputID").text(inputs[0]);
        });
      
       
        });

</script>