<script type="text/javascript" src="/scripts/category_modify.js"></script>
<br /><br />
<div id="view-content" class='wiki'>
	<div class='content'>
		<div id="category_list">
					<h4><a id="add_category_link">Add a New Category >></a></h4>
					<?php if($this->categories):?>
						<?php echo $this->categories; ?>
					<?php endif;?>	
		</div>
	</div>
	
   <div id="edit_window" class="editWindow ui-dialog ui-widget ui-widget-content ui-corner-all" tabindex="0">
   	<a class="ui-dialog-titlebar-close ui-corner-all" href="#" role="button" unselectable="on" style="-moz-user-select: none;">
		<span class="ui-icon ui-icon-closethick" id="close_btn" unselectable="on" style="-moz-user-select: none;">close</span>
	</a>
   	<div id="dialog-modal-43" class="ui-dialog-content ui-widget-content" style="width: auto; min-height: 0px; height: 200px">
    	<form valign="top" align="center" id="category_form" action="<?php echo $this->escape($this->form->getAction()) ?>"
          method="<?php echo $this->escape($this->form->getMethod()) ?>"
          enctype="multipart/form-data">
	        <table align="center" class="category_table" id="select_action">
	                <?php echo $this->form->cname; ?>
	             	<?php echo $this->form->status; ?>
	                <?php echo $this->form->parent_id; ?>
	             	<?php echo $this->form->category_id; ?>
	                <tr id="editWindow_buttons" class="category_table_static">
	                    <td><?php echo $this->form->submit; ?></td>
	                </tr>
	        </table>
		 </form>
	 </div>
	 </div> 
</div>

