<script type="text/javascript" src="/scripts/category_modify.js"></script>
<br /><br />
<div id="view-content" class='wiki'>
	<div class='content'>
	    <h1 align="center">Categories</h1>
		<div id="category_list">
					<?php if($this->categories):?>
						<?php echo $this->categories; ?>
					<?php endif;?>		
		</div>
	</div>
	
   <div id="edit_window" class="editWindow" tabindex="0">
    	<form valign="top" align="center" id="category_form" action="<?php echo $this->escape($this->form->getAction()) ?>"
          method="<?php echo $this->escape($this->form->getMethod()) ?>"
          enctype="multipart/form-data">
	        <table align="center" class="category_table" id="select_action">
	                <?php echo $this->form->cname; ?>
	             	<?php echo $this->form->status; ?>
	                <?php echo $this->form->parent_id; ?>
	             	<?php echo $this->form->category_id; ?>
	                <tr id="editWindow_buttons" class="category_table_static">
	                    <td><?php echo $this->form->submit; ?></td>
	                </tr>
	        </table>
		 </form>
	 </div> 
</div>

