<script type="text/javascript" src="/scripts/jquery.ui.core.js"></script>
<script type="text/javascript" src="/scripts/jquery.ui.dialog.js"></script>
<script>
$(document).ready(function()
{
    $( "#dialog:ui-dialog" ).dialog( "destroy" );
    
    var dialog_modal=document.getElementById('dialog-modal');
	dialog_modal.style.display="none";  

    $('#add-new-workbook').click(function() {
		$( "#dialog-modal" ).dialog({
			height: 280,
            width: 450,
			modal: true
		});
	});

    <?php foreach($this->tree as $tree4):?>
        <?php foreach($tree4 as $tree4_key => $tree4_val):?>
            var dialog_modal_<?=$tree4_key?>=document.getElementById('dialog-modal-<?=$tree4_key?>');
            dialog_modal_<?=$tree4_key?>.style.display="none"; 

            $('#edit-workbook-<?=$tree4_key?>').click(function() {
                $( "#dialog-modal-<?=$tree4_key?>" ).dialog({
                    height: 280,
                    width: 450,
                    modal: true
                });
            });
            <?php endforeach;?>
    <?php endforeach;?>

});

function deleteItem(itemId)
{
    if(window.confirm('You will delete this element if you click OK!'))
    {
        location.href="/category/edit/behavior/del/wb/<?=$this->wb?>/self_id/" + itemId;
    }
}

function restoreItem(itemId, parentId)
{
    if(window.confirm('Are you sure to restore this item?'))
    {
        location.href="/category/edit/behavior/restore/wb/<?=$this->wb?>/self_id/" + itemId + "/parent_id/" + parentId;
    }
}
</script>
<br />&nbsp;&nbsp;
<?php if($this->note):?>
<font color="red">* <?=$this->note?></font>
<br /><br />
<?php endif;?>
<?php if($this->top_level): ?>
    <select name="top_level" onChange="location=this.value">
        <?php foreach($this->top_level as $top_key => $top_val):?>
        <option value="/category/index/wb/<?=$top_key?>" <?php if($this->wb == $top_key){echo "selected='selected'";} ?>><?=$top_val?></option>
        <?php endforeach;?>
    </select>
<?php endif; ?>
&nbsp;&nbsp;&nbsp;<a id="add-new-workbook" href="#"><u>Create new category</u></a>
<?php if($this->tree):?>
<br />
<div>
<table class="hide" border="0" cellpadding="0" cellspacing="3">
	<tbody>
		<tr>
			<td valign="top" width="100%">
				<table class="width100" cellspacing="1">
					<tbody>
						<tr>
							<td><br />
                                <?php foreach($this->tree as $tree):?>
                                    <?php foreach($tree as $tree_key => $tree_val):?>
                                        <?php echo "<a id='edit-workbook-".$tree_key."' href='#'>".$tree_val."</a><br /><br />";?>
                                    <?php endforeach;?>
                                <?php endforeach;?>
                            </td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>
</div>
<br /><br /><br />&nbsp;&nbsp;Deleted List<br />
<div align="center">
<table class="hide" border="0" cellpadding="0" cellspacing="3">
	<tbody>
		<tr>
			<td valign="top" width="100%">
				<table class="width100" cellspacing="1">
					<tbody>
						<tr>
							<td class="form-title">Parent</td>
							<td class="form-title">Category Name</td>
							<td class="form-title">Delete By</td>
							<td class="form-title">Delete Time</td>
							<td class="form-title">Action</td>
						</tr>
						<?php if($this->delete_list):
								$n = 1;
								foreach($this->delete_list as $delete_list):
						?>
						<tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
							<td class="center"><span class="small"><?=$delete_list['parent_name']?></span></td>
							<td class="center"><span class="small"><?=$delete_list['cname']?></span></td>
							<td class="center"><span class="small"><?=$delete_list['del_who_realname']?></span></td>
							<td class="center"><span class="small"><?=$delete_list['del_time']?></span></td>
							<td class="center"><span class="small"><a href="javascript:restoreItem('<?=$delete_list['id']?>', '<?=$delete_list['parent_id']?>');"><u>Restore</u></a></span></td>
						</tr>
						<?php
								endforeach;
							endif;
						?>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>
</div>
<?php endif;?>
<div id="dialog-modal" title="Add new category">
    <form action="/category/edit" method="POST">
        <br />Category Name: <input type="text" name="child_name" />&nbsp;
        <input type="hidden" name="behavior" value="add" />
        <input type="hidden" name="self_id" value="" />
        <input type="hidden" name="wb" value="<?=$this->wb?>" />
        <input type="submit" value="Add" />
    </form>
</div>

<?php $tree_model = new Category();?>

<?php foreach($this->tree as $tree2):?>
    <?php foreach($tree2 as $tree2_key => $tree2_val):?>
    <?php $tree2_info = $tree_model ->GetOne($tree2_key);?>

        <div id="dialog-modal-<?=$tree2_key?>" title="Edit Category">
            <form action="/category/edit" method="POST">
                <br />Parent: 
                <select name="parent_id">
                    <option value="">Category Root</option>
                    <?php $tree_clean = $tree_model ->CleanUnavailable($tree2_key, $this->tree)?>
                    <?php foreach($tree_clean as $tree3):?>
                        <?php foreach($tree3 as $tree3_key => $tree3_val):?>
                            <?php if($tree3_key != $tree2_key):?>
                                <option value="<?=$tree3_key?>" <?php if($tree2_info['parent_id'] == $tree3_key){echo "selected='selected'";} ?>><?=$tree3_val?></option>
                            <?php endif;?>
                        <?php endforeach;?>
                    <?php endforeach;?>
                </select><br /><br />
                Work Name: <input type="text" name="self_name" value="<?=$tree2_info['cname']?>" /><br /><br />
                Add Child: <input type="text" name="child_name" value="" /><br /><br />
                <input type="hidden" name="self_id" value="<?=$tree2_key?>" />
                <input type="hidden" name="behavior" value="add" />
                <input type="hidden" name="wb" value="<?=$this->wb?>" />
                <input type="submit" value="Submit" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:deleteItem('<?=$tree2_key?>');"><font color="red">Delete</font></a>
            </form>
        </div>

    <?php endforeach;?>
<?php endforeach;?>