<script>
$('document').ready(function(){
    $('select[name=workbook_top]').change(function(){
        var workbookID = $('select[name=workbook_top]').val();
        ajaxGetWorkbook(workbookID);
    })
    
    $('select[name=workbook]').change(function(){
        var workID = $('select[name=workbook]').val();
        ajaxGetStaff(workID);
    })
})

function ajaxGetWorkbook(workbookID)
{
    $.ajax({
        type:"POST",
        url:"<?=$this->base_url?>/index/get-workbook",
        data:{workbookID:workbookID},
        success:function(response){
            if(response != ''){
                $('select[name=workbook]').html(response);
                $('select[name=workbook]').show();
            }
        }
    })
}

function ajaxGetStaff(workID)
{
    $.ajax({
        type:"POST",
        url:"<?=$this->base_url?>/index/get-staff",
        data:{workID:workID},
        success:function(response){
            if(response != ''){
                $('select[name=staff]').html(response);
                $('select[name=staff]').show();
            }
        }
    })
}

function deleteStaff(id, type, uid)
{
    if(window.confirm('You will delete this staff from this ticket if you click OK!'))
    {
        location.href="/index/del-staff/id/" + id + "/type/" + type + "/uid/" + uid;
    }
}
</script>

<p><a href="/index/view/type/<?=$this->type?>/id/<?=$this->id?>"><< Back to ticket</a></p>
<?php if($this->notice):?>
<font color="#ff0000"><strong>* <?php echo $this->notice;?></strong></font><br /><br />
<?php endif;?>
<div align="center"><H3>Division of ticket: <?=$this->ticket_array['title'];?></H3></div>
<table class="hide" border="0" cellpadding="0" cellspacing="3">
	<tbody>
		<tr>
			<td valign="top" width="100%">
				<table class="width100" cellspacing="1">
					<tbody>
						<tr>
							<td class="form-title">Creator</td>
							<td class="form-title">Workbook</td>
							<td class="form-title">Staff</td>
							<td class="form-title">Notes</td>
							<td class="form-title">Status</td>
							<td class="form-title">Difficulty</td>
							<td class="form-title">Est. Time</td>
							<td class="form-title">Used Time</td>
							<td class="form-title">Action</td>
						</tr>
						<?php if($this->list):
								$n = 1;
								foreach($this->list as $list):
						?>
						<tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
							<td class="center"><span class="small"><?=$list['creator']?></span></td>
							<td class="center"><span class="small"><?=$list['workbook']?></span></td>
							<td class="center"><span class="small"><?=$list['user_id']?></span></td>
							<td class="center"><span class="small"><?=$list['notes']?></span></td>
							<td class="center"><span class="small"><?=$list['status_text']?></span></td>
							<td class="center"><span class="small"><?=$list['diff']?></span></td>
							<td class="center"><span class="small"><?=$list['suggestion_hour']?> <?php if($_SESSION["Zend_Auth"]["storage"]->id == $list['creator_id']):?><a href="/index/division-edit/tid/<?=$this->id?>/kid/<?=$list['tid']?>/type/<?=$this->type?>"><img src="/images/edit.png" border="0" title="Update Estimated Time" alt="Update Estimated Time" /></a><?php endif;?></span></td>
							<td class="center">
                                <?php if($list['status']):?>
                                    <?php $kpi_time = new KpiTicketsTime();?>
                                    <iframe src="/index/recent-used-time/uid/<?=$list['uid'];?>" frameborder="0" width="77" height="18" border="0" marginheight="0" marginwidth="0" scrolling="no" paddingheight="0"></iframe>
                                <?php else:?>
                                    <span class="small"><?=$list['used_time']?></span>
                                <?php endif;?>
                            </td>
							<td class="center"><span class="small"><?php if($_SESSION["Zend_Auth"]["storage"]->id == $list['creator_id']):?><a href="javascript:deleteStaff('<?=$this->id?>', '<?=$this->type?>', <?=$list['uid']?>)">Del</a><?php endif;?></span></td>
						</tr>
						<?php
								endforeach;
							endif;
						?>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>


<div align="center"><H3>Assign Staff</H3></div>
<form id='divisionForm' name='divisionForm' action="/index/division/type/<?=$this->type?>/id/<?=$this->id?>" method="post">
	<table class="width100" cellspacing="1">
		<tbody>
			<tr class="row-2">
				<td class="category">Difficulty</td>
				<td>
                    <select name="diff" id="diff">
                        <?php foreach($this->diff_array as $diff_array_key => $diff_array_val):?>
                        <option value="<?=$diff_array_key?>" <?php if(3==$diff_array_key){echo "selected='selected'";}?>><?=$diff_array_val?></option>
                        <?php endforeach;?>
                    </select>
                </td>
            </tr>
			<tr class="row-1">
				<td class="category">Workbook</td>
				<td>
                    <select name="workbook_top" id="workbook_top">
                        <?php foreach($this->workbook_top as $workbook_top_key => $workbook_top_val):?>
                        <option value="<?=$workbook_top_key?>"><?=$workbook_top_val?></option>
                        <?php endforeach;?>
                    </select>
                </td>
            </tr>
			<tr class="row-2">
				<td class="category">Work</td>
				<td>
                    <select name="workbook" id="workbook">
                    </select>
                </td>
            </tr>
			<tr class="row-1">
				<td class="category">Staff</td>
				<td>
                    <select name="staff" id="staff">
                    </select>
                </td>
            </tr>
			<tr class="row-2">
				<td class="category">Staff Type</td>
				<td>
                    <select name="stype" id="stype">
                        <?php foreach($this->stype as $stype_key => $stype_val):?>
                        <option value="<?=$stype_key?>"><?=$stype_val?></option>
                        <?php endforeach;?>
                    </select>
                </td>
            </tr>
			<tr class="row-1">
				<td class="category">Notes</td>
				<td><input type="text" name="notes" id="notes" /></td>
            </tr>
			<tr class="row-2">
				<td class="category">Est. Time</td>
				<td>
                    <select name="shour" id="shour">
                        <?php foreach($this->shour as $shour_key => $shour_val):?>
                        <option value="<?=$shour_key?>"><?=$shour_val?></option>
                        <?php endforeach;?>
                    </select>:
                    <select name="smin" id="smin">
                        <?php foreach($this->smin as $smin_key => $smin_val):?>
                        <option value="<?=$smin_key?>"><?=$smin_val?></option>
                        <?php endforeach;?>
                    </select>:00&nbsp;&nbsp;&nbsp;<i>[hh:mm:ss]</i>
                </td>
            </tr>
			<tr class="row-1">
				<td colspan="2"><input type="hidden" name="source" value="fm" /><input type="submit" value="Add Staff" /></td>
            </tr>
		</tbody>
	</table>
</form>