<p><a href="/index/division/type/<?=$this->type?>/id/<?=$this->tid?>"><< Back to division</a></p>
<?php if($this->notice):?>
<font color="#ff0000"><strong>* <?php echo $this->notice;?></strong></font><br /><br />
<?php endif;?>
<div align="center"><H3>Update Estimated Time</H3></div>
<form id='divisionForm' name='divisionForm' action="/index/division-edit/type/<?=$this->type?>/tid/<?=$this->tid?>/kid/<?=$this->kid?>" method="post">
	<table class="width100" cellspacing="1">
		<tbody>
			<tr class="row-2">
				<td class="category">Est. Time</td>
				<td>
                    <select name="shour" id="shour">
                        <?php foreach($this->shour as $shour_key => $shour_val):?>
                        <option value="<?=$shour_key?>" <?php if($shour_key==$this->shour_selected){echo "selected='selected'";}?>><?=$shour_val?></option>
                        <?php endforeach;?>
                    </select>:
                    <select name="smin" id="smin">
                        <?php foreach($this->smin as $smin_key => $smin_val):?>
                        <option value="<?=$smin_key?>" <?php if($smin_key==$this->smin_selected){echo "selected='selected'";}?>><?=$smin_val?></option>
                        <?php endforeach;?>
                    </select>:00&nbsp;&nbsp;&nbsp;<i>[hh:mm:ss]</i>
                </td>
            </tr>
			<tr class="row-1">
				<td colspan="2"><input type="hidden" name="source" value="fm" /><input type="submit" value="Update" /></td>
            </tr>
		</tbody>
	</table>
</form>