<script type="text/javascript">
$(function() {
	var availableTags = [<?=$this->users_array?>];
	function split(val) {
		return val.split(/,\s*/);
	}
	function extractLast(term) {
		return split(term).pop();
	}
	
	$("#supervisor").autocomplete({
		minLength: 0,
		source: function(request, response) {
			// delegate back to autocomplete, but extract the last term
			response($.ui.autocomplete.filter(availableTags, extractLast(request.term)));
		},
		focus: function() {
			// prevent value inserted on focus
			return false;
		},
		select: function(event, ui) {
			var terms = split( this.value );
			// remove the current input
			terms.pop();
			// add the selected item
			terms.push( ui.item.value );
			// add placeholder to get the comma-and-space at the end
			terms.push("");
			this.value = terms.join(", ");
			return false;
		}
	});
});
</script>

<br />
<?php if($this->notice):?>
<font color="#ff0000"><strong>* <?php echo $this->notice;?></strong></font><br /><br />
<?php endif;?>
<form action="/users/add" method="post">
	<table class="width100" cellspacing="1">
		<tbody>
			<tr>
				<td class="form-title" colspan="4">Add User</td>
			</tr>		
			<tr class="row-1">
				<td class="category">User Name *</td>
				<td colspan="3"><?php echo $this->form->username;?></td>
			</tr>			
			<tr class="row-2">
				<td class="category">Password *</td>
				<td colspan="3"><?php echo $this->form->passwd;?></td>
			</tr>
			<tr class="row-1">
				<td class="category">Repeat it *</td>
				<td colspan="3"><?php echo $this->form->passwd_r;?></td>
			</tr>
			<tr class="row-2">
				<td class="category">Displayed Name *</td>
				<td colspan="3"><?php echo $this->form->realname;?></td>
			</tr>
			<tr class="row-1">
				<td class="category">First Name</td>
				<td colspan="3"><?php echo $this->form->first_name;?></td>
			</tr>
			<tr class="row-2">
				<td class="category">Last Name</td>
				<td colspan="3"><?php echo $this->form->last_name;?></td>
			</tr>
			<tr class="row-1">
				<td class="category">Title</td>
				<td colspan="3"><?php echo $this->form->team_title;?></td>
			</tr>
			<tr class="row-2">
				<td class="category">Supervisor</td>
				<td colspan="3"><?php echo $this->form->supervisor;?></td>
			</tr>
			<tr class="row-1">
				<td class="category">Email</td>
				<td colspan="3"><?php echo $this->form->email;?></td>
			</tr>
			<tr class="row-2">
				<td class="category">Skype</td>
				<td colspan="3"><?php echo $this->form->skype;?></td>
			</tr>
			<tr class="row-1">
				<td class="category">Department *</td>
				<td colspan="3"><?php echo $this->form->department;?></td>
			</tr>
			<tr class="row-2">
				<td class="category">Level of Tickets *</td>
				<td colspan="3"><?php echo $this->form->level_view_tickets;?></td>
			</tr>
			<tr class="row-1">
				<td class="category">Level of MGT *</td>
				<td colspan="3"><?php echo $this->form->level_mgt;?></td>
			</tr>
			<tr class="row-2">
				<td class="category">Status *</td>
				<td colspan="3"><?php echo $this->form->status;?></td>
			</tr>
			<tr class="row-1">
				<td class="category">New Ticket Notice *</td>
				<td colspan="3"><?php echo $this->form->new_alert;?></td>
			</tr>
			<tr class="row-2">
				<td class="category">Email Reminder *</td>
				<td colspan="3"><?php echo $this->form->reminder;?></td>
			</tr>
			<tr class="row-1">
				<td class="category">Default List *</td>
				<td colspan="3"><?php echo $this->form->default_list;?></td>
			</tr>
			</tr>		
			<tr class="row-2">
				<td colspan="4"><?php echo $this->form->submit;?></td>
			</tr>
		</tbody>
	</table>
</form>
