<div align="center">
<table class="hide" border="0" cellpadding="0" cellspacing="3">
	<tbody>
		<tr>
			<td valign="top" width="100%">
				<table class="width100" cellspacing="1">
					<tbody>
						<tr>
							<td class="form-title">Real Name</td>
							<td class="form-title">User Name</td>
							<td class="form-title">Department</td>
							<td class="form-title">Supervisor</td>
							<td class="form-title">Level of Tickets</td>
							<td class="form-title">Level of MGT</td>
							<td class="form-title">Email</td>
							<td class="form-title">Status</td>
							<td class="form-title">Action</td>
						</tr>
						<?php if($this->list):
								$n = 1;
								foreach($this->list as $list):
						?>
						<tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
							<td class="center"><span class="small"><?=$list['realname']?></span></td>
							<td class="center"><span class="small"><?=$list['username']?></span></td>
							<td class="center"><span class="small"><?=$list['department']?></span></td>
							<td class="center"><span class="small"><?=$list['supervisor']?></span></td>
							<td class="center"><span class="small"><?=$list['level_view_tickets']?></span></td>
							<td class="center"><span class="small"><?=$list['level_mgt']?></span></td>
							<td class="center"><span class="small"><?=$list['email']?></span></td>
							<td class="center"><span class="small"><?=$list['status']?></span></td>
							<td class="center"><span class="small">
                                    <?php if(3 == $_SESSION["Zend_Auth"]["storage"]->level_mgt):?>
                                    <a href="/users/edit/id/<?=$list['id']?>">Edit</a> / 
                                    <?php endif;?>
                                    <a href="/users/division/id/<?=$list['id']?>">Division</a></span></td>
						</tr>
						<?php
								endforeach;
							endif;
						?>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>
</div>
