<?php
$this->Scripts = <<<EOF
<script type="text/javascript" src="/scripts/ckeditor4.2/ckeditor.js"></script>
<script type="text/javascript">
    $(function(){
        var content = $('#content').html();
        $('#title').click(function(){
            $(this).select();     
        });
        var tosubmit=false;
        $(window).bind('beforeunload ',function() {
            if(CKEDITOR.instances.content.checkDirty()&&tosubmit==false){
               return "Your edition are not be saved, are you sure to leave this page?";
            }
        });
        $('#topic_form').submit(function(){
            tosubmit=true;
        });
    });
</script>
EOF;
?>


<div class="wiki">
    <form id="topic_form" action="<?php echo $this->escape($this->form->getAction()) ?>"
              method="<?php echo $this->escape($this->form->getMethod()) ?>"
              enctype="multipart/form-data">
        <table width="100%">
            <tbody>
                <tr>
                    <td valign="top"><?php echo $this->form->title; ?></td>
                    <td valign="top"><?php echo $this->form->category; ?></td>
                </tr>
                <tr>
                    <td colspan="2">
                        <?php echo $this->form->content; ?>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td style="text-align: right;"><?php echo $this->form->submit; ?></td>
                </tr>
            </tbody>
        </table>
    </form>
    <script type="text/javascript">
        var edit = CKEDITOR.replace('content',{
            extraPlugins: 'autogrow',
            height:'500px',
            filebrowserBrowseUrl: '/scripts/ckfinder/ckfinder.html',
            filebrowserImageBrowseUrl: '/scripts/ckfinder/ckfinder.html?Type=Images',
            filebrowserFlashBrowseUrl: '/scripts/ckfinder/ckfinder.html?Type=Flash',
            filebrowserUploadUrl: '/scripts/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
            filebrowserImageUploadUrl: '/scripts/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
            filebrowserFlashUploadUrl: '/scripts/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
        });
    </script>
</div>