<?php
$this->Scripts = $this->Scripts.<<<EOF
<!--[if !IE 6]>-->
    <script type="text/javascript" src="/scripts/ckeditor4.2/ckeditor.js"></script>
<!--<![endif]-->
<!--[if lte IE 6]>
<script type="text/javascript" src="/ckeditor/ckeditor.js"></script>
<![endif]-->  
<script type="text/javascript">
    $(function(){
       /* $('#title').click(function(){
            $(this).select();
            $(this).css('color','#000')

        });*/
        var tosubmit=false;
        var category_val = $('#category').val();
        $(window).bind('beforeunload ',function() {
            if(CKEDITOR.instances.content.checkDirty()&&tosubmit==false){
               return "Your edition are not be saved, are you sure to leave this page?";
            }
        });
        $('#topic_form').submit(function(){
            tosubmit=true;
            var category_new_val = $('#category').val();
            if(!CKEDITOR.instances.content.checkDirty()&&category_val==category_new_val){
                alert('It seem no need to submit,because the content do not change:)');
                tosubmit=false;
                return false;
            } else {
                return true;
            }
        });
    });
</script>
EOF;
$this->Css = <<<EOF
<!--[if lt IE 8]>
    <style tyle="text/css">
        .wiki input, .wiki select {
            font-family: Verdana, Arial, Helvetica, sans-serif;
            font-size:100%; 
            line-height:34px !important;
        }
        .wiki select {
            margin-top:1px;
            font-size: 25px !important;
        }
    </style>    
<![endif]-->
EOF;
/* @var $this Zend_View */
?>


<div class="wiki">
    <?php if(isset($this->message)):?>
        <div class="message ui-widget ui-widget-content ui-corner-all"><?php echo $this->message ?></div>
    <?php endif;?>
    <div class="tool-bar" style="margin-top: 15px;margin-right:6px;">
        <div class="fr">
            <span class="ui-icon ui-icon-arrowthick-1-w fl"></span>
            <a href="<?php echo $this->ActionUrl('detail',array('id'=>$this->tid));?>" style="line-height: 16px;">Back to topic</a>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
    <form id="topic_form" action="<?php echo $this->escape($this->form->getAction()) ?>"
              method="<?php echo $this->escape($this->form->getMethod()) ?>"
              enctype="multipart/form-data">
        <table width="100%">
            <tbody>
                <tr>
                    <td valign="top"><?php echo $this->form->title; ?></td>
                    <td valign="top" width="25%"><?php echo $this->form->category; ?></td>
                </tr>
                <tr>
                    <td colspan="2">
                        <?php echo $this->form->content; ?>
                        <?php echo $this->form->tid; ?>
                        <?php echo $this->form->vid; ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align: right;"><button class="back" onclick="location.href='<?php echo $this->ActionUrl('detail',array('id'=>$this->tid)); ?>';return false;">back to topic</button><?php echo $this->form->submit; ?></td>
                </tr>
            </tbody>
        </table>
    </form>
    <script type="text/javascript">
        var edit = CKEDITOR.replace('content',{
            extraPlugins: 'autogrow',
            height:'500px',
            language : 'en',
            filebrowserBrowseUrl: '/scripts/ckfinder/ckfinder.html',
            filebrowserImageBrowseUrl: '/scripts/ckfinder/ckfinder.html?Type=Images',
            filebrowserFlashBrowseUrl: '/scripts/ckfinder/ckfinder.html?Type=Flash',
            filebrowserUploadUrl: '/scripts/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
            filebrowserImageUploadUrl: '/scripts/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
            filebrowserFlashUploadUrl: '/scripts/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
        });
        CKEDITOR.editorConfig = function( config ) {
            config.toolbarGroups = [
		{ name: 'document',    groups: [ 'mode', 'document', 'doctools' ] },
		{ name: 'clipboard',   groups: [ 'clipboard', 'undo' ] },
		{ name: 'editing',     groups: [ 'find', 'selection', 'spellchecker' ] },
		{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
                { name: 'links' },
		{ name: 'insert' },
                { name: 'colors' },
		{ name: 'paragraph',   groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ] },
		{ name: 'styles' },
		{ name: 'tools' },
		{ name: 'others' }
            ];
            config.removeButtons = 'Cut,Copy,Paste,Undo,Redo,Anchor,Underline,Strike,Subscript,Superscript,Iframe,Flash,Smiley';
            config.removeDialogTabs = 'link:advanced;image:advanced;image:Link';
            config.autoGrow_onStartup = true;
        };
    </script>
</div>