<div class="wiki">
    <div class="history tb-style">
<!--        <pre><?//=print_r($this->data)?></pre>-->
        <div class="tool-bar" style="margin-bottom: 15px;">
            <div class="fr">
                <span class="ui-icon ui-icon-arrowthick-1-w fl"></span>
                <a href="<?php echo $this->ActionUrl('detail',array('id'=>$this->tid));?>" style="line-height: 16px;">Back to topic</a>
                <div class="clear"></div>
            </div>
            <div class="fl">
                <span class="strong">History Of "<a href="<?php echo $this->ActionUrl('detail',array('id'=>$this->data[0]['tid']));?>"><?php echo $this->data[0]['title'] ?></a>"</span>
            </div>
            <div class="clear"></div>
        </div>
        <table width="100%" cellpadding="0" cellspacing="1">
            <tbody>
                <tr>
                    <th><a href="<?php echo $this->ActionUrl('history', array('id'=>$this->data[0]['tid'],'orderBy' =>'version_id','sortOrder'=>$this->sort)) ?>">Version</a></th>
                    <th><a href="<?php echo $this->ActionUrl('history', array('id'=>$this->data[0]['tid'],'orderBy' =>'update_time','sortOrder'=>$this->sort)) ?>">Update Time</a></th>
                    <th><a href="<?php echo $this->ActionUrl('history', array('id'=>$this->data[0]['tid'],'orderBy' =>'update_name','sortOrder'=>$this->sort)) ?>">Contributor</a></th>
                    <th>Topic</th>
                    <th><a href="<?php echo $this->ActionUrl('history', array('id'=>$this->data[0]['tid'],'orderBy' =>'update_time','sortOrder'=>$this->sort)) ?>">From</a></th>
                    <th>On Show</th>
                </tr>
                <?php foreach ($this->data as $value):?>
                <tr>
                    <td><a  title="Click to view this version" href="<?php echo $this->ActionUrl('revert',array('id'=>$value['tid'],'version'=>$value['vid']));?>"><?php echo $value['version_id'] ?></a></td>
                    <td><?php echo $value['update_time'] ?></td>
                    <td><?php echo $value['update_name'] ?></td>
                    <td><a  title="Click to view this version" href="<?php echo $this->ActionUrl('revert',array('id'=>$value['tid'],'version'=>$value['vid']));?>"><?php echo $value['title'] ?></a></td>
                    <td>
                        <?php if($value['preversion_id']): ?>
                        <a  title="Click to view this version" href="<?php echo $this->ActionUrl('revert',array('id'=>$value['tid'],'version'=>$value['preversion_id']));?>">
                             <?php echo $value['preversion_id']?>
                        </a>
                        <?php else:?>
                                <span title="This is original version">original</span>
                        <?php endif;?>
                    </td>
                    <td align="center">
                        <?php if($value['is_default']):?> 
                            <span class="ui-icon ui-icon-circle-check" style="margin: 0 auto;"></span>
                        <?php else:?>
                            &nbsp;
                        <?php endif;?>
                    </td>
                </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    </div>
</div>
