<?php
$this->Css = <<<EOF
    <link type="text/css" rel="stylesheet" href="/scripts/ckeditor4.2/contents_view.css">        
EOF;
?>
<div class='wiki limitWidth'>
    <?php if($this->data['content']):?>
    <div class="navigation">
        <?php 
            $topicUrl = $this->ActionUrl('detail',array('id'=>$this->data['tid']));
        ?>
        <?php echo "{$this->categoryPath} &gt; <a href='{$topicUrl}'>{$this->data['title']}</a> > Version{$this->data['version_id']}";?>
    </div>
    <div class="detail">
        <div class="tool-bar">
            <div class="fr">
                <span class="ui-icon ui-icon-arrowthick-1-w fl"></span>
                <a href="<?php echo $this->ActionUrl('history',array('id'=>$this->data['tid']));?>" style="line-height: 16px;">Back to history</a>
                <div class="clear"></div>
            </div>
            <div class="fl">
                <?php if($this->data['prevId']!=NULL):?>
                <div class="fl mr10" style="line-height: 16px;"><a href="<?php echo $this->ActionUrl('revert',array('id'=>$this->data['tid'],'version'=>$this->data['prevId']));?>">←</a></div>
                <?php endif;?>
                <div class="fl strong mr10" style="line-height: 16px;">Version ID:<?php echo  $this->data['version_id'];?> </div>
                <?php if($this->data['is_default']==TRUE): ?>
                <div class="fl mr10"><span class="ui-icon ui-icon-circle-check" title="Current Version"></span></div>
                <?php endif;?>
                <?php if($this->data['nextId']!=NULL):?>
                <div class="fl" style="line-height: 16px;"><a href="<?php echo $this->ActionUrl('revert',array('id'=>$this->data['tid'],'version'=>$this->data['nextId']));?>">→</a></div>
                <?php endif;?>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
        <h1 class="title">
        <?php echo $this->data['title']; if($this->data['is_default']==TRUE) echo '<i style="color:#CF1E1E;font-size:12px;">(Current Version)</i>'; ?>
        </h1>
        <h4 class="info">
            Author:<?php echo $this->data['creator_name'] ?>&nbsp;|&nbsp;
            Create Time:<?php echo $this->data['created_time'] ?>&nbsp;|&nbsp;
            Last Update Time:<?php echo $this->data['update_time'] ?>&nbsp;|&nbsp;
            Update By:<?php echo $this->data['update_name'] ?>
        </h4>
        <div class="content cke_editable cke_editable_themed cke_contents_ltr cke_show_borders">
            <?php echo $this->data['content'] ?>
        </div>
        <div class="handle">
            <table>
                <tbody>
                    <tr>
                        <?php if($this->data['prevId']!=NULL):?>
                        <td><a class="button-style" href="<?php echo $this->ActionUrl('revert',array('id'=>$this->data['tid'],'version'=>$this->data['prevId']));?>">Previous Version</a></td>
                        <?php endif; ?>
                        <?php if($this->data['nextId']!=NULL):?>
                        <td><a class="button-style" href="<?php echo $this->ActionUrl('revert',array('id'=>$this->data['tid'],'version'=>$this->data['nextId']));?>">Next Version</a></td>
                        <?php endif; ?>
                        <?php if($this->data['is_default']!=TRUE):?>
                        <?php $uid = Zend_Auth::getInstance()->getStorage()->read()->id?>
                        <?php if($this->data['creator_uid']===$uid):?><td><a id="revert" class="button-style btn-red" href="<?php echo $this->ActionUrl('set-default',array('id'=>$this->data['tid'],'version'=>$this->data['vid']));?>">Revert to this version</a></td><?php endif;?>
                        <script type="text/javascript">
                             $('#revert').click(function(){
                                 if(confirm("This handle will revert to this version and create a new history item,would you like to do that?")){
                                     return true;
                                 }
                                 return false;
                             });
                        </script>
                        <?php endif; ?>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="tool-bar">
            <div class="fr">
                <span class="ui-icon ui-icon-arrowthick-1-w fl"></span>
                <a href="<?php echo $this->ActionUrl('history',array('id'=>$this->data['tid']));?>" style="line-height: 16px;">Back to history</a>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <?php else: ?>
    <div class="shadow mt15 p15 radius">
        This version was not found
    </div>
    <?php endif; ?>
</div>