<br /><br />
<div id="wiki">
        <h1 align="center">Contributor</h1>
	<div>
		<div style="margin-left: 10%">
				<?php if($this->contributor):?>
					<?php foreach($this->contributor as $key => $val):?>
							<h3>Name:</h3><?=$val['contributor_name']?>
							<h3>Department:</h3><?=$val['department_name']?>
							<h3>Total Contributions:</h3><?=$val['contributions']?>
					<?php endforeach;?>			
				<?php endif;?>
		</div>
		<div class='tb-style'>
		<h2>Latest Topic Contributions</h1>
				<table width="60%" align="center" cellspacing="1" >
					<tbody>
							<tr>
								<th class="form-title" width="70%" >Topic</td>
								<th class="form-title" width="30%" >Date</td>
							</tr>
							<?php if($this->latest_topics):?>
								<?php foreach($this->latest_topics as $key => $val):?>
								<tr>
									<td><?=$val['topic_title']?></td>
									<td><?=$val['date_created']?></td>
								</tr>
								<?php endforeach;?>			
							<?php endif;?>	
					</tbody>
				</table>
		</div>
</div>