<br /><br />
<div class="wiki">
        <h1 align="center">Search Results</h1>
	<div class="tb-style">
		<table width="100%" align="center" cellspacing="1">
			<tbody>
				<tr>
					<th><a href="<?php echo $this->page_urls["column_1"] ?>">Category</a></th>
					<th><a href="<?php echo $this->page_urls["column_2"] ?>">Topic</a></th>
					<th><a href="<?php echo $this->page_urls["column_3"] ?>">Created By</a></th>
					<th><a href="<?php echo $this->page_urls["column_4"] ?>">Creation Time</a></th>
					<th><a href="<?php echo $this->page_urls["column_5"] ?>">Last Updated</a></th>
				</tr>
				<?php if($this->results):?>
					<?php foreach($this->results as $key => $val):?>
						<tr class="row-1">
							<td><?=$val['category_name']?></td>
							<td><?=$val['topic_title']?></td>
							<td><?=$val['contributor_name']?></td>
							<td><?=$val['creation_time']?></td>
							<td><?=$val['last_updated']?></td>
						</tr>
					<?php endforeach;?>			
				<?php endif;?>
			</tbody>
		</table>
	</div>
	<div align="right" >
		<?php if($this->pages):
				if($this->pages>2):$maxPageNav = $this->current_page + 3; else: $maxPageNav = $this->current_page; endif; ?>
					<?php for($i = $this->current_page-3; $i<=$maxPageNav; $i++):?>
						<?php if(($i > 0)&&($i <= $this->pages)):?>
						<a href="<?php echo $this->page_urls["page_".$i] ?>"> <?= $i?></a>
						<?php endif; ?>
					<?php endfor;?>	
		<?php endif; ?>
	</div>
</div>