<script charset="utf-8" src="/scripts/kindeditor/kindeditor.js"></script>
<script charset="utf-8" src="/scripts/kindeditor/lang/en.js"></script>
<script>
	var editor;
	KindEditor.ready(function(K) {
		editor = K.create('textarea[name="contents"]', {
			allowFileManager : true
		});
	});
</script>
<script type="text/javascript">
$(function() {
	$('#dead_line').datepicker({
		numberOfMonths: 2,
		showButtonPanel: true,
		dateFormat: 'yy-mm-dd'
	});
});
</script>
<script type="text/javascript">
$(document).ready(function(){
if($("#trackList").text()!="")
{
    $("#track-content").show();
}
$('#trackRadio-0').click(
	function(){
		//alert("i'm here!!");
		 // $('#track-content').slideUp('slow');
		  $("#track-content").hide();
	   });
$('#trackRadio-1').click(
		function(){
			$("#track-content").show();
		   // $('#registerform').slideDown('slow');
		    //$('#emailform').slideUp('slow');
   });

});
</script>
<script type="text/javascript">
$(function() {
	var availableTags = [<?=$this->users_array?>];
	function split(val) {
		return val.split(/,\s*/);
	}
	function extractLast(term) {
		return split(term).pop();
	}
    
	$("#participants").autocomplete({
		minLength: 0,
		source: function(request, response) {
			// delegate back to autocomplete, but extract the last term
			response($.ui.autocomplete.filter(availableTags, extractLast(request.term)));
		},
		focus: function() {
			// prevent value inserted on focus
			return false;
		},
		select: function(event, ui) {
			var terms = split( this.value );
			// remove the current input
			terms.pop();
			// add the selected item
			terms.push( ui.item.value );
			// add placeholder to get the comma-and-space at the end
			terms.push("");
			this.value = terms.join(", ");
			return false;
		}
	});
});
</script>

<script>
function addFileInput() {
	var get_num = (document.getElementById("atmt_record").value);
	var new_num = parseFloat(get_num) + 1;
	var atmt_id = "atmt" + new_num;

 	document.getElementById("atmt_record").value = new_num;
 	document.getElementById(atmt_id).style.display ='block';
 	
 	if(20 == new_num)
 	{
 		document.getElementById("atmt_say").style.display ='none';
 	}
}

</script>

<br />
<?php if($this->notice):?>
<font color="#ff0000"><strong>* <?php echo $this->notice;?></strong></font><br /><br />
<?php endif;?>
<?php $n = 1;?>
<form action="/requests/add" method="post" enctype="multipart/form-data">
	<table class="width100" cellspacing="1">
		<tbody>
			<tr>
				<td class="form-title" colspan="4">Add Request</td>
			</tr>
			<tr class="row-<?php echo (2-$n%2); $n++;?>">
				<td class="category">Request Type</td>
				<td colspan="3">&nbsp;<?=$this->category[1]?><?php echo $this->form->category;?></td>
			</tr>
			<tr class="row-<?php echo (2-$n%2); $n++;?>">
				<td class="category">Dead Line</td>
				<td colspan="3"><?php echo $this->form->dead_line;?></td>
			</tr>
			<tr class="row-<?php echo (2-$n%2); $n++;?>">
				<td class="category">Priority</td>
				<td colspan="3"><?php echo $this->form->priority;?></td>
			</tr>
			<tr class="row-<?php echo (2-$n%2); $n++;?>">
				<td class="category">Participants</td>
				<td colspan="3"><?php echo $this->form->participants;?></td>
			</tr>
                        <?php if(!empty($this->get_form_elements)):?>
                            <?php foreach($this->get_form_elements as $get_form_elements_key => $get_form_elements_val):?>
                                <tr class="row-<?php echo (2-$n%2); $n++;?>">
                                    <td class="category"><?=$get_form_elements_val[1]?> <?php if($get_form_elements_val[0]){echo "*";} ?></td>
                                    <td colspan="3"><?php $tag_name = "additional".$get_form_elements_key; echo $this->form->$tag_name;?></td>
                                </tr>
                            <?php endforeach;?>
                        <?php endif;?>
			<tr class="row-<?php echo (2-$n%2); $n++;?>">
				<td class="category">Title *</td>
				<td colspan="3"><?php echo $this->form->title;?></td>
			</tr>
			<tr class="row-<?php echo (2-$n%2); $n++;?>">
				<td class="category">Contents</td>
				<td colspan="3"><?php echo $this->form->contents;?></td>
			</tr>		
			<tr class="row-<?php echo (2-$n%2); $n++;?>">
				<td class="category">Attachment</td>
				<td colspan="3">
                                        <?php for($n=1;$n<21;$n++):?>
                                        <?php $attach_name = "attachment".$n;?>
					<div id="atmt<?=$n?>"<?php if($n>1){ ?> style="display:none;"<?php }?>><?php echo $this->form->$attach_name;?></div>
					<?php endfor;?>
                                        <div id="atmt_say"><a href="javascript:addFileInput();">Attach another File</a></div>
					<input type="hidden" name="atmt_record" id="atmt_record" value="1" />
				</td>
			</tr>		
			<tr class="row-<?php echo (2-$n%2); $n++;?>">
				<td colspan="4"><?php echo $this->form->submitx;?></td>
			</tr>
		</tbody>
	</table>
</form>