<br />
&nbsp;
    <select name="category" onchange="window.location.href=this.value">
        <option value="/login/set-cookie-redirect/target/1">Category</option>
    <?php foreach($this->category_tree as $category_tree): ?>
        <?php foreach($category_tree as $category_tree_key=>$category_tree_val): ?>
            <option value="/login/set-cookie-redirect/target/1/cookie_value/<?=$category_tree_key?>" <?php if($this->category == $category_tree_key){echo "selected='selected'";}?>><?=$category_tree_val?></option>
        <?php endforeach;?>
    <?php endforeach;?>
    </select>
&nbsp;
<?php if($this->category): ?>
<a href="/requests/add/type/add/category/<?=$this->category?>">
<?php else: ?>
<a href="#" onclick="alert('Please select category first.');">
<?php endif; ?>
<img src="/images/add.png" border="0" title="Add" alt="Add" /></a>
<div align="center">
<form name="form1" id="form1" method="post" />
	<input type="hidden" name="p_type" value="<?=$this->p_type?>" />
	<input type="hidden" name="p_page" value="<?=$this->p_page?>" />
	<table class="hide" border="0" cellpadding="0" cellspacing="1">
		<tbody>
			<tr>
				<td valign="top" width="100%">
					<table class="width100" cellspacing="1">
						<tbody>
							<tr>
								<td class="form-title" width="40">ID</td>
								<td class="form-title">Subject</td>
								<td class="form-title">Category</td>
								<td class="form-title" width="80">Status</td>
								<td class="form-title" width="80">Priority</td>
								<td class="form-title" width="100">Dead Line</td>
								<td class="form-title" width="150">Created</td>
								<td class="form-title" width="150">Closed</td>
							</tr>
							<?php if($this->list):
									$n = 1;
									foreach($this->list as $list):
							?>
							<tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
								<td class="center"><span class="small"><?=$list['id']?></span></td>
								<td class="left"><span class="small"><a href="/requests/view/type/index/id/<?=$list['id']?>"><?=$list['composer']?>: <?=$list['title']?></a></span></td>
								<td class="center"><span class="small"><?=$list['category']?></span></td>
								<td class="center"><span class="small"><?=$list['status']?></span></td>
								<td class="center"><span class="small"><?=$list['priority']?></span></td>
								<td class="center"><span class="small"><?=$list['deadline']?></span></td>
								<td class="center"><span class="small"><?=$list['created_date']?></span></td>
								<td class="center"><span class="small"><?=$list['closed_date']?></span></td>
							</tr>
							<?php
									endforeach;
								endif;
							?>
						</tbody>
					</table>
				</td>
			</tr>
		</tbody>
	</table>
</form>
</div>
<div align="right"><?php if($this->can_newer):?><a href="?page=<?=$this->newer?>">< older</a><?php endif; ?><?php if($this->can_older):?>&nbsp;&nbsp;&nbsp;<a href="?page=<?=$this->older?>">newer ></a><?php endif; ?></div>
<script>setTimeout("self.location.reload();",300000);</script>
