<graph xaxisname='Hour in a day' yaxisname='Task Qty' hovercapbg='DEDEBE' hovercapborder='889E6D' bgColor="E8E8E8" rotateNames='0' numdivlines='9' divLineColor='CCCCCC' divLineAlpha='80' decimalPrecision='0' showAlternateHGridColor='1' AlternateHGridAlpha='30' AlternateHGridColor='CCCCCC' caption='Task Distribution' subcaption='<?=$this->date_from?> to <?=$this->date_to?>' >
   <categories font='Arial' fontSize='11' fontColor='000000'>
      <category name='0' hoverText='North America'/>
      <category name='1' />
      <category name='2' />
      <category name='3' />
      <category name='4' />
      <category name='5' />
      <category name='6' />
      <category name='7' />
      <category name='8' />
      <category name='9' />
      <category name='10' />
      <category name='11' />
      <category name='12' />
      <category name='13' />
      <category name='14' />
      <category name='15' />
      <category name='16' />
      <category name='17' />
      <category name='18' />
      <category name='19' />
      <category name='20' />
      <category name='21' />
      <category name='22' />
      <category name='23' />
   </categories>
   <dataset seriesname='<?=$this->user_name?>' color='FDC12E'>
      <?php foreach($this->self_data as $self_data):?>
        <set value='<?=$self_data?>' />
      <?php endforeach;?>
   </dataset>
    <dataset seriesname='Team' color='56B9F9'>
      <?php foreach($this->team_data as $team_data):?>
        <set value='<?=$team_data?>' />
      <?php endforeach;?>
   </dataset>
</graph>