<script type="text/javascript">
$(function() {
	$('#d_from').datepicker({
		showButtonPanel: true,
		dateFormat: 'yy-mm-dd'
	});
});

$(function() {
	$('#d_to').datepicker({
		showButtonPanel: true,
		dateFormat: 'yy-mm-dd'
	});
});
</script>
<?php if($this->notice):?>
<br />
<font color="#ff0000"><strong>* <?php echo $this->notice;?></strong></font>
<?php endif;?>
<div align="center">
    <H3>KPI Report Review Center</H3>
    <form action="/kpi/review" method="POST">
    <table class="hide" border="0" cellpadding="0" cellspacing="1">
		<tbody>
			<tr>
				<td valign="top" width="50%">
					<table class="width900" cellspacing="1" align="center">
						<tbody>
							<tr>
								<td class="form-title" style="text-align: left;" colspan="2">Search</td>
							</tr>
							<tr class="row-2">
								<td class="right" width="50%"><span class="small">From</td>
								<td class="left" width="50%"><span class="small"><input type="text" name="d_from" id="d_from" /></td>
							</tr>
							<tr class="row-1">
								<td class="right"><span class="small">To</td>
								<td class="left"><span class="small"><input type="text" name="d_to" id="d_to" /></td>
							</tr>
							<tr class="row-2">
								<td class="right"><span class="small">User</td>
								<td class="left"><span class="small">
                                        <select name="d_user" id="d_user">
                                            <option value="all">ALL STAFFS</option>
                                            <?php foreach($this->user_list as $user_list_key => $user_list_val):?>
                                                <option value="<?=$user_list_key?>" <?php if($_SESSION["Zend_Auth"]["storage"]->id == $user_list_key){echo "selected='selected'";}?>><?=$user_list_val?></option>
                                            <?php endforeach;?>
                                        </select>
                                </td>
							</tr>
							<tr class="row-1">
								<td class="center" colspan="2"><input type="submit" value="Submit" /></td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
		</tbody>
	</table>
    </form>
</div>
<br /><br /><br />