<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link rel="SHORTCUT ICON" href="/images/favicon.ico">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$this->title?> - <?=$this->system_title?></title>
<link href="/styles/login.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="layer01_holder">
  <div id="left"></div>
  <div id="center"></div>
  <div id="right"></div>
</div>

<div id="layer02_holder">
  <div id="left"></div>
  <div id="center"></div>
  <div id="right"></div>
</div>

<div id="layer03_holder">
  <div id="left"></div>
  <div id="center">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td>LOGIN<br /><br /></td>
  </tr>
  <tr>
    <td><form action="/login/index" method="POST" name="form1" id="form1"><input type="hidden" name="url" value="<?=$this->url?>" />
      <label><span>ID</span>
        <input name="username" type="text" id="username" />
        <div class="clear"></div>
      </label>
      <label><span>PW</span>
      <input type="password" name="passwd" id="passwd" style="margin-top:5px;" />
       <div class="clear"></div>
      </label>
      <label>
       <input type="submit" name="button" id="button" value="Login" />
      </label>
    </form>    </td>
  </tr>
</table>
  </div>
  <div id="right"></div>
</div>

<div id="layer04_holder">
  <div id="left"></div>
  <div id="center">Copyright © <?=date("Y");?> CrazySales</div>
  <div id="right"></div>
</div>

<script type="text/javascript">
try{document.getElementById('username').focus();}catch(e){}
</script>

</body>
</html>
