<br />
<?php if($this->notice):?>
<font color="#ff0000"><strong>* <?php echo $this->notice;?></strong></font><br /><br />
<?php endif;?>
<form action="/group/edit/id/<?php echo $this->data->id;?>" method="post">
	<table class="width100" cellspacing="1">
		<tbody>
			<tr>
				<td class="form-title" colspan="4">Edit Group: <?php echo $this->data->gname;?><?php echo $this->form->id;?></td>
			</tr>		
			<tr class="row-1">
				<td class="category">Group Name</td>
				<td colspan="3"><?php echo $this->data->gname;?></td>
			</tr>			
			<tr class="row-2">
				<td class="category">Members</td>
				<td colspan="3"><?php echo $this->form->members;?></td>
			</tr>
			</tr>		
			<tr class="row-1">
				<td colspan="4"><?php echo $this->form->submit;?></td>
			</tr>
		</tbody>
	</table>
</form>
