<br /><br />
<div class="wiki">
        <h1 align="center">Recent Updates</h1>
	<div class="tb-style">
		<table width="100%" align="center" cellspacing="1">
			<tbody>
				<tr>
					<th width="15%"><a href="<?php echo $this->page_urls["column_1"] ?>">Date</a></th>
					<th width="30%"><a href="<?php echo $this->page_urls["column_2"] ?>">Category</a></th>
					<th width="40%"><a href="<?php echo $this->page_urls["column_3"] ?>">Topic</a></th>
					<th width="15%"><a href="<?php echo $this->page_urls["column_4"] ?>">Contributor</a></th>
				</tr>
				<?php if($this->recent_updates):?>
					<?php foreach($this->recent_updates as $key => $val):?>
						<tr class="row-1">
							<td><?=$val['date_created']?></td>
							<td><a href=""><?=$val['parent_name']?> > <?=$val['category_name']?></a></td>
							<td><a href=""><?=$val['topic_title']?></a></td>
							<td><a href="/wiki/topic/show-contributor/?userid=<?=$val['user_id']?>"><?=$val['contributor_name']?></a></td>
						</tr>
					<?php endforeach;?>			
				<?php endif;?>
			</tbody>
		</table>
	</div>
	<div align="right" style="margin-right: 10%">
		<?php if($this->pages):
				if($this->pages>2):$maxPageNav = $this->current_page + 3; else: $maxPageNav = $this->current_page; endif; ?>
					<?php for($i = $this->current_page-3; $i<=$maxPageNav; $i++):?>
						<?php if(($i > 0)&&($i <= $this->pages)):?>
						<a href="<?php echo $this->page_urls["page_".$i] ?>"> <?= $i?></a>
						<?php endif; ?>
					<?php endfor;?>	
		<?php endif; ?>
	</div>
</div>