<br /><br />
<div class="wiki">
        <h1 align="center">Contributor</h1>
		<div style="margin-left: 10%">
				<?php if($this->contributor):?>
					<?php foreach($this->contributor as $key => $val):?>
							<h3>Name:</h3><?=$val['contributor_name']?>
							<h3>Department:</h3><?=$val['department_name']?>
							<h3>Total Contributions:</h3><?=$val['contributions']?>
					<?php endforeach;?>			
				<?php endif;?>
		</div>

		<h2 class="center_header">Latest Topic Contributions</h2>
		<div class="tb-style">
				<table>
						<tr>
							<th>Topic</td>
							<th>Date</td>
						</tr>
							<?php if($this->latest_topics):?>
								<?php foreach($this->latest_topics as $key => $val):?>
								<tr>
									<td><?=$val['topic_title']?></td>
									<td><?=$val['date_created']?></td>
								</tr>
								<?php endforeach;?>			
							<?php endif;?>	
				</table>
		</div>
</div>