<br />
<?php if($this->notice):?>
<font color="#ff0000"><strong>* <?php echo $this->notice;?></strong></font><br /><br />
<?php endif;?>
<form action="/departments/index/act/ud" method="post">
	<table class="width100" cellspacing="1">
		<tbody>
			<tr>
				<td class="form-title" style="text-align: right;">Department ID</td>
				<td class="form-title" colspan="3" style="text-align: left;">Department Name</td>
			</tr>
			<?php if($this->departments):?>
				<?php foreach($this->departments as $key => $val):?>
					<tr class="row-1">
						<td class="category"><?=$key?></td>
						<td colspan="3"><input type="text" name="pname[<?=$key?>]" value="<?=$val?>" /></td>
					</tr>
				<?php endforeach;?>			
			<?php endif;?>
			<tr class="row-2">
				<td class="category">Add</td>
				<td colspan="3"><input type="text" name="nname" /></td>
			</tr>		
			<tr class="row-1">
				<td colspan="4"><input type="submit" value="Update" /></td>
			</tr>
		</tbody>
	</table>
</form>
