<?php if($this->notice):?>
<p><font color="#ff0000"><strong>* <?php echo $this->notice;?></strong></font></p>
<?php else:?>
<br />
<?php endif;?>
<form action="/profile/index" method="post">
	<table class="width100" cellspacing="1">
		<tbody>
			<tr>
				<td class="form-title" colspan="4">My Profile<?php echo $this->form->id;?></td>
			</tr>
			<tr class="row-2">
				<td class="category">Password</td>
				<td colspan="3"><?php echo $this->form->passwd;?> * Left it blank if you don't want to update password</td>
			</tr>
			<tr class="row-1">
				<td class="category">Repeat it</td>
				<td colspan="3"><?php echo $this->form->passwd_r;?></td>
			</tr>
			<tr class="row-2">
				<td class="category">Real Name</td>
				<td colspan="3"><?php echo $this->form->realname;?></td>
			</tr>
			<tr class="row-1">
				<td class="category">Email</td>
				<td colspan="3"><?php echo $this->form->email;?></td>
			</tr>
			<tr class="row-2">
				<td class="category">Skype</td>
				<td colspan="3"><?php echo $this->form->skype;?></td>
			</tr>
			<tr class="row-1">
				<td class="category">Receive Ticket Notice</td>
				<td colspan="3"><?php echo $this->form->new_alert;?></td>
			</tr>
			<tr class="row-2">
				<td class="category">Email Reminder</td>
				<td colspan="3"><?php echo $this->form->reminder;?></td>
			</tr>
			<tr class="row-1">
				<td class="category">Default List</td>
				<td colspan="3"><?php echo $this->form->default_list;?></td>
			</tr>
			<tr class="row-2">
				<td colspan="4"><?php echo $this->form->submit;?></td>
			</tr>
		</tbody>
	</table>
</form>
