<script type="text/javascript">
$(function() {
	var availableTags = [<?=$this->users_array?>];
	function split(val) {
		return val.split(/,\s*/);
	}
	function extractLast(term) {
		return split(term).pop();
	}
    
	$("#ttrainer").autocomplete({
		minLength: 0,
		source: function(request, response) {
			// delegate back to autocomplete, but extract the last term
			response($.ui.autocomplete.filter(availableTags, extractLast(request.term)));
		},
		focus: function() {
			// prevent value inserted on focus
			return false;
		},
		select: function(event, ui) {
			var terms = split( this.value );
			// remove the current input
			terms.pop();
			// add the selected item
			terms.push( ui.item.value );
			// add placeholder to get the comma-and-space at the end
			terms.push("");
			this.value = terms.join(", ");
			return false;
		}
	});
});
</script>

<script>
function deleteItem(itemId)
{
    if(window.confirm('You will delete this calendar if you click OK!'))
    {
        location.href="/training/delarr/id/" + itemId;
    }
}
</script>

<br />
<?php if($this->notice):?>
<font color="#ff0000"><strong>* <?php echo $this->notice;?></strong></font><br /><br />
<?php endif;?>
<form action="/training/edit-submit" method="post">
	<table class="width100" cellspacing="1">
		<tbody>
			<tr>
				<td class="form-title" colspan="4">Edit Calendar</td>
			</tr>
			<tr class="row-2">
				<td class="category">Status</td>
				<td>
                    <input type="radio" name="tstatus" value="1" <?php if(1 == $this->original_tstatus){echo "checked='checked'";}?>>Available
                    &nbsp;&nbsp;
                    <input type="radio" name="tstatus" value="2" <?php if(2 == $this->original_tstatus){echo "checked='checked'";}?>>Closed
                </td>
			</tr>
			<tr class="row-1">
				<td class="category">Topic</td>
                <td>
                    <select name="ttitle">
                        <option value="">Choose..</option>
                        <?php foreach ($this->library_list as $library_list_key => $library_list_val):?>
                            <option value="<?=$library_list_key?>" <?php if($library_list_key==$this->original_ttitle){echo "selected='selected'";}?>><?=$library_list_val?></option>
                        <?php endforeach;?>
                    </select> *
                </td>
			</tr>
            <tr class="row-2">
			      <td class="category">Date</td>
			      <td>
                    <select name="tyear">
                        <?php foreach ($this->year_array as $year_array):?>
                            <option value="<?=$year_array?>" <?php if($year_array==$this->original_tyear){echo "selected='selected'";}elseif($year_array==date("Y")){echo "selected='selected'";}?>><?=$year_array?></option>
                        <?php endforeach;?>
                    </select>
                    &nbsp;&nbsp;
                    <select name="tmonth">
                        <?php foreach ($this->month_array as $month_array):?>
                            <option value="<?=$month_array?>" <?php if($month_array==$this->original_tmonth){echo "selected='selected'";}elseif($month_array==date("m")){echo "selected='selected'";}?>><?=$month_array?></option>
                        <?php endforeach;?>
                    </select>
                    &nbsp;&nbsp;
                    <select name="tday">
                        <?php foreach ($this->day_array as $day_array):?>
                            <option value="<?=$day_array?>" <?php if($day_array==$this->original_tday){echo "selected='selected'";}elseif($day_array==date("d")){echo "selected='selected'";}?>><?=$day_array?></option>
                        <?php endforeach;?>
                    </select> *
                  </td>
			</tr>
			<tr class="row-1">	
			      <td class="category">Time</td>
			      <td>
                    <select name="thour">
                        <?php foreach ($this->hour_array as $hour_array):?>
                            <option value="<?=$hour_array?>" <?php if($hour_array==$this->original_thour){echo "selected='selected'";}elseif($hour_array==date("H")){echo "selected='selected'";}?>><?=$hour_array?></option>
                        <?php endforeach;?>
                    </select>
                    &nbsp;&nbsp;
                    <select name="tmin">
                        <?php foreach ($this->min_array as $min_array):?>
                            <option value="<?=$min_array?>" <?php if($min_array==$this->original_tmin){echo "selected='selected'";}?>><?=$min_array?></option>
                        <?php endforeach;?>
                    </select> *
                  </td>
			</tr>
			<tr class="row-2">
				<td class="category">Place</td>
				<td>
                    <select name="tplace">
                        <option value="">Choose..</option>
                        <?php foreach ($this->place_list as $place_list_key => $place_list_val):?>
                            <option value="<?=$place_list_key?>" <?php if($place_list_key==$this->original_tplace){echo "selected='selected'";}?>><?=$place_list_val?></option>
                        <?php endforeach;?>
                    </select> *
                </td>
			</tr>
			<tr class="row-1">
				<td class="category">Language</td>
				<td>
                    <select name="tlang">
                        <option value="">Choose..</option>
                        <?php foreach ($this->lang_list as $lang_list_key => $lang_list_val):?>
                            <option value="<?=$lang_list_key?>" <?php if($lang_list_key==$this->original_tlang){echo "selected='selected'";}?>><?=$lang_list_val?></option>
                        <?php endforeach;?>
                    </select> *
                </td>
			</tr>
			<tr class="row-2">
				<td class="category">Open Class</td>
				<td>
                    <input type="radio" name="topen" value="1" <?php if("0" != $this->original_topen){echo "checked='checked'";}?>>Yes
                    &nbsp;&nbsp;
                    <input type="radio" name="topen" value="0" <?php if("0" == $this->original_topen){echo "checked='checked'";}?>>No
                </td>
			</tr>
			<tr class="row-1">
				<td class="category">Tips</td>
				<td><input type="text" name="ttip" size="100" value="<?=$this->original_ttip?>"></td>
			</tr>
			<tr class="row-2">
				<td class="category">Trainer(s)</td>
				<td>
                    <input type="text" name="ttrainer" id="ttrainer" value="<?php if($this->original_ttrainer){echo $this->original_ttrainer;}else{echo $this->initial_trainer;}?>" size="70" class="ui-autocomplete-input" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true"> *
                </td>
			</tr>
			<tr class="row-1">
				<td class="category">Trainee(s)</td>
				<td>
                    <?php foreach($this->trainee_list as $trainee_list):?>
                        <?php $n = 0;?>
                        <H4><?=$trainee_list['dept']?></H4>
                        <?php foreach($trainee_list['members'] as $members_key => $members_val):?>
                            <input type="checkbox" name="ttrainee[<?=$members_key?>]" <?php if(in_array($members_key, $this->original_ttrainee)){echo "checked='checked'";}?>><?=$members_val?>&nbsp;&nbsp;
                            <?php 
                                $n += 1;
                                if(0 == $n%5)
                                {
                                    echo "<br />";
                                }
                            ?>
                            
                        <?php endforeach;?>
                    <?php endforeach;?>
                </td>
			</tr>
			<tr class="row-2">
                <td colspan="1"><input type="hidden" name="arr_id" value="<?=$this->arr_id;?>" /><input type="submit" value="Update" /></td>
                <td colspan="1"><div align="right"><a href="javascript:deleteItem('<?=$this->arr_id?>');"><font color="red">Delete</font></a></div></td>
			</tr>
		</tbody>
	</table>
</form>