<div align="center">

<table class="hide" border="0" cellpadding="0" cellspacing="3">
	<tbody>
		<tr>
			<td valign="top" width="100%">
				<table class="width100" cellspacing="1">
					<tbody>
						<tr>
							<td class="form-title">Time</td>
							<td class="form-title">Category</td>
							<td class="form-title">Title</td>
							<td class="form-title">Score</td>
						</tr>
						<?php if($this->list):
								$n = 1;
								foreach($this->list as $list):
						?>
						<tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
							<td class="center"><span class="small"><?=$list['adate']?></span></td>
							<td class="center"><span class="small"><?=$list['lcategory']?></span></td>
							<td class="center"><span class="small"><?=$list['ltitle']?></span></td>
							<td class="center"><span class="small"><?=$list['escore']?></span></td>
						</tr>
						<?php
								endforeach;
							endif;
						?>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>
</div>
