<style>
.create_calendar {
    background: none repeat scroll 0 0 #EA9F1E;
    border: 1px solid #EA9F1E;
    color: #FFFFFF;
    cursor: pointer;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 12px;
}
</style>
<script>
        function create_calendar()
        {
            window.location.href = "/training/add";
        }
	</script>
&nbsp;
<form method="GET" name="vform" id="vform" onsubmit="create_calendar();return false;">
	<input type="button" value="Create Calendar" class="create_calendar" onclick="create_calendar();" />
</form>
<div align="center">

<table class="hide" border="0" cellpadding="0" cellspacing="3">
	<tbody>
		<tr>
			<td valign="top" width="100%">
				<table class="width100" cellspacing="1">
					<tbody>
						<tr>
							<td class="form-title">Time</td>
							<td class="form-title">Category</td>
							<td class="form-title">Title</td>
							<td class="form-title">Trainer</td>
							<td class="form-title">Place</td>
							<td class="form-title">Me?</td>
							<td class="form-title">Open</td>
							<td class="form-title">Language</td>
							<td class="form-title">Status</td>
							<td class="form-title">Action</td>
						</tr>
						<?php if($this->list):
								$n = 1;
								foreach($this->list as $list):
						?>
						<tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
							<td class="center"><span class="small"><font color="<?=$list['expired']?>"><?=$list['agm_time']?></font></span></td>
							<td class="center"><span class="small"><font color="<?=$list['expired']?>"><?=$list['agm_category']?></font></span></td>
							<td class="center"><span class="small"><font color="<?=$list['expired']?>"><?=$list['agm_title']?></font></span></td>
							<td class="center"><span class="small"><font color="<?=$list['expired']?>"><?=$list['agm_trainer']?></font></span></td>
							<td class="center"><span class="small"><font color="<?=$list['expired']?>"><?=$list['agm_place']?></font></span></td>
							<td class="center"><span class="small"><font color="<?=$list['expired']?>"><?=$list['agm_me']?></font></span></td>
							<td class="center"><span class="small"><font color="<?=$list['expired']?>"><?=$list['agm_open']?></font></span></td>
							<td class="center"><span class="small"><font color="<?=$list['expired']?>"><?=$list['agm_lang']?></font></span></td>
							<td class="center"><span class="small"><font color="<?=$list['expired']?>"><?=$list['agm_status']?></font></span></td>
							<td class="center"><span class="small"><a href="/training/view/id/<?=$list['agm_id']?>"><img src="/images/view.png" border="0" title="View" alt="View" /></a><?php if($list['high_auth']):?>&nbsp;&nbsp;&nbsp;<a href="/training/edit/id/<?=$list['agm_id']?>"><img src="/images/edit.png" border="0" title="Edit" alt="Edit" /></a>&nbsp;&nbsp;&nbsp;<a href="/training/score/id/<?=$list['agm_id']?>"><img src="/images/chart.png" border="0" title="Score" alt="Score" /></a><?php endif;?></span></td>
						</tr>
						<?php
								endforeach;
							endif;
						?>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>
</div>
