<p><a href="/training/library"><< Back</a></p>
	<table class="width100" cellspacing="1">
		<tbody>
			<tr>
				<td class="form-title" colspan="2"><?php echo $this->topic['title'];?></td>
			</tr>
			<tr class="row-1">
				<td class="category">Category</td>
				<td><?php echo $this->topic['category'];?></td>
			</tr>	
			<tr class="row-2">
				<td class="category">Title</td>
				<td><?php echo $this->topic['title'];?></td>
			</tr>	
			<tr class="row-1">
				<td class="category">Author</td>
				<td><?php echo $this->topic['author'];?></td>
			</tr>
			<tr class="row-2">
				<td class="category">Description</td>
				<td><?php echo $this->topic['description'];?></td>
			</tr>		
			<tr class="row-1">
				<td class="category">Attachment</td>
				<td><?php echo $this->attachments;?>
				</td>
			</tr>
		</tbody>
	</table>

<iframe id="callFile" name="callFile" style="width: 0px; height: 0px; border: 0px"></iframe>