<script charset="utf-8" src="/scripts/kindeditor/kindeditor.js"></script>
<script charset="utf-8" src="/scripts/kindeditor/lang/en.js"></script>
<script>
	var editor;
	KindEditor.ready(function(K) {
		editor = K.create('textarea[name="description"]', {
			allowFileManager : true
		});
	});
</script>
<script type="text/javascript">
$(function() {
	var availableTags = [<?=$this->users_array?>];
	function split(val) {
		return val.split(/,\s*/);
	}
	function extractLast(term) {
		return split(term).pop();
	}
    
	$("#author").autocomplete({
		minLength: 0,
		source: function(request, response) {
			// delegate back to autocomplete, but extract the last term
			response($.ui.autocomplete.filter(availableTags, extractLast(request.term)));
		},
		focus: function() {
			// prevent value inserted on focus
			return false;
		},
		select: function(event, ui) {
			var terms = split( this.value );
			// remove the current input
			terms.pop();
			// add the selected item
			terms.push( ui.item.value );
			// add placeholder to get the comma-and-space at the end
			terms.push("");
			this.value = terms.join(", ");
			return false;
		}
	});
});
</script>

<script>
function addFileInput() {
	var get_num = (document.getElementById("atmt_record").value);
	var new_num = parseFloat(get_num) + 1;
	var atmt_id = "atmt" + new_num;

 	document.getElementById("atmt_record").value = new_num;
 	document.getElementById(atmt_id).style.display ='block';
 	
 	if(20 == new_num)
 	{
 		document.getElementById("atmt_say").style.display ='none';
 	}
}

</script>

<br />
<?php if($this->notice):?>
<font color="#ff0000"><strong>* <?php echo $this->notice;?></strong></font><br /><br />
<?php endif;?>
<form action="/training/lib-add" method="post" enctype="multipart/form-data">
	<table class="width100" cellspacing="1">
		<tbody>
			<tr>
				<td class="form-title" colspan="4">Add Topic</td>
			</tr>
			<tr class="row-1">
				<td class="category">Category</td>
				<td><?php echo $this->form->category;?> *</td>
			</tr>
            <tr class="row-2">
			      <td class="category">Title</td>
			      <td><?php echo $this->form->title;?> *</td>
			</tr>
			<tr class="row-1">	
			      <td class="category">Author</td>
			      <td><?php echo $this->form->author;?> *</td>
			</tr>
			<tr class="row-2">
				<td class="category">Description</td>
				<td><?php echo $this->form->description;?></td>
			</tr>
			<tr class="row-1">
				<td class="category">Attachment</td>
				<td colspan="3">
                    <div id="atmt1"><?php echo $this->form->attachment1;?></div>
					<div id="atmt2" style="display:none;"><?php echo $this->form->attachment2;?></div>
					<div id="atmt3" style="display:none;"><?php echo $this->form->attachment3;?></div>
					<div id="atmt4" style="display:none;"><?php echo $this->form->attachment4;?></div>
					<div id="atmt5" style="display:none;"><?php echo $this->form->attachment5;?></div>
					<div id="atmt6" style="display:none;"><?php echo $this->form->attachment6;?></div>
					<div id="atmt7" style="display:none;"><?php echo $this->form->attachment7;?></div>
					<div id="atmt8" style="display:none;"><?php echo $this->form->attachment8;?></div>
					<div id="atmt9" style="display:none;"><?php echo $this->form->attachment9;?></div>
					<div id="atmt10" style="display:none;"><?php echo $this->form->attachment10;?></div>
					<div id="atmt11" style="display:none;"><?php echo $this->form->attachment11;?></div>
					<div id="atmt12" style="display:none;"><?php echo $this->form->attachment12;?></div>
					<div id="atmt13" style="display:none;"><?php echo $this->form->attachment13;?></div>
					<div id="atmt14" style="display:none;"><?php echo $this->form->attachment14;?></div>
					<div id="atmt15" style="display:none;"><?php echo $this->form->attachment15;?></div>
					<div id="atmt16" style="display:none;"><?php echo $this->form->attachment16;?></div>
					<div id="atmt17" style="display:none;"><?php echo $this->form->attachment17;?></div>
					<div id="atmt18" style="display:none;"><?php echo $this->form->attachment18;?></div>
					<div id="atmt19" style="display:none;"><?php echo $this->form->attachment19;?></div>
					<div id="atmt20" style="display:none;"><?php echo $this->form->attachment20;?></div>
					<div id="atmt_say"><a href="javascript:addFileInput();">Attach another File</a></div>
					<input type="hidden" name="atmt_record" id="atmt_record" value="1" />
				</td>
			</tr>		
			<tr class="row-2">
				<td colspan="4"><?php echo $this->form->submitx;?></td>
			</tr>
		</tbody>
	</table>
</form>