<style>
.create_topic {
    background: none repeat scroll 0 0 #EA9F1E;
    border: 1px solid #EA9F1E;
    color: #FFFFFF;
    cursor: pointer;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 12px;
}
</style>
<script>
        function create_topic()
        {
            window.location.href = "/training/lib-add";
        }
	</script>
&nbsp;
<form method="GET" name="vform" id="vform" onsubmit="create_topic();return false;">
	<input type="button" value="Create Topic" class="create_topic" onclick="create_topic();" />
</form>
<div align="center">

<table class="hide" border="0" cellpadding="0" cellspacing="3">
	<tbody>
		<tr>
			<td valign="top" width="100%">
				<table class="width100" cellspacing="1">
					<tbody>
						<tr>
							<td class="form-title">Category</td>
							<td class="form-title">Title</td>
							<td class="form-title">Author</td>
							<td class="form-title">Last Updated Time</td>
							<td class="form-title">Action</td>
						</tr>
						<?php if($this->list):
								$n = 1;
								foreach($this->list as $list):
						?>
						<tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
							<td class="center"><span class="small"><?=$list['lib_category']?></span></td>
							<td class="center"><span class="small"><?=$list['lib_title']?></span></td>
							<td class="center"><span class="small"><?=$list['lib_author']?></span></td>
							<td class="center"><span class="small"><?=$list['lib_udate']?></span></td>
							<td class="center"><span class="small"><a href="/training/lib-view/id/<?=$list['lib_id']?>"><img src="/images/view.png" border="0" title="View" alt="View" /></a><?php if($list['high_auth']):?>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/training/lib-edit/id/<?=$list['lib_id']?>"><img src="/images/edit.png" border="0" title="Edit" alt="Edit" /></a><?php endif;?></span></td>
						</tr>
						<?php
								endforeach;
							endif;
						?>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>
</div>
