<br />
<?php if($this->notice):?>
<font color="#ff0000"><strong>* <?php echo $this->notice;?></strong></font><br /><br />
<?php endif;?>
<form action="/training/score-submit" method="post">
	<table class="width100" cellspacing="1">
		<tbody>
			<tr>
				<td class="form-title" colspan="2">Add score for the training: <?=$this->t_name['ltitle']?> on <?=$this->t_name['adate']?></td>
			</tr>
            <?php foreach($this->list as $list):?>
            <?php $n = 1?>
			<tr class="row-<?=$n?>">
				<td class="category"><?=$list['user_name']?></td>
                <td>
                    <select name="score[<?=$list['id']?>]">
                        <?php foreach($this->score_array as $score_array_key => $score_array_val):?>
                            <option value="<?=$score_array_key?>" <?php if(strval($score_array_key)==strval($list['score'])){echo "selected='selected'";}?>><?=$score_array_val?></option>
                        <?php endforeach;?>
                    </select>
                </td>
			</tr>
            <?php if(1==$n){$n = 2;}else{$n = 1;}?>
            <?php endforeach;?>
			<tr class="row-2">
                <td colspan="2"><input type="hidden" name="arr_id" value="<?=$this->arr_id;?>" /><input type="submit" value="Submit" /></td>
			</tr>
		</tbody>
	</table>
</form>