<br />
	<table class="width100" cellspacing="1">
		<tbody>
			<tr>
				<td class="form-title" colspan="4">View Calendar</td>
			</tr>
			<tr class="row-2">
				<td class="category">Status</td>
                <td><?=$this->original_tstatus?></td>
			</tr>
			<tr class="row-1">
				<td class="category">Topic</td>
                <td><a href="/training/lib-view/id/<?=$this->original_lib_id?>"><?=$this->original_ttitle?> <img src="/images/view.png" border="0" title="View Training Topic" alt="View Training Topic"></a></td>
			</tr>
            <tr class="row-2">
			      <td class="category">Date / Time</td>
			      <td><?=$this->original_ttime?></td>
			</tr>
			<tr class="row-1">
				<td class="category">Place</td>
				<td><?=$this->original_tplace?></td>
			</tr>
			<tr class="row-2">
				<td class="category">Language</td>
				<td><?=$this->original_tlang?></td>
			</tr>
			<tr class="row-1">
				<td class="category">Open Class</td>
				<td><?=$this->original_topen?></td>
			</tr>
			<tr class="row-2">
				<td class="category">Tips</td>
				<td><?=$this->original_ttip?></td>
			</tr>
			<tr class="row-1">
				<td class="category">Trainer(s)</td>
				<td><?=$this->original_ttrainer?></td>
			</tr>
			<tr class="row-2">
				<td class="category">Trainee(s)</td>
				<td><?=$this->original_ttrainee?></td>
			</tr>
		</tbody>
	</table>